let clientUser=null, clientProfile=null, clientMessageChannel=null;
const C$=id=>document.getElementById(id); const Cstatus=(id,m)=>C$(id).textContent=m||'';
function money(n,c='GHS'){return `${c} ${Number(n||0).toFixed(2)}`}
async function loadClient(){
 const {data:{user}}=await supabaseClient.auth.getUser(); if(!user){C$('clientLogin').classList.remove('hidden');C$('clientApp').classList.add('hidden');return;}
 clientUser=user; const {data:profile}=await supabaseClient.from('clients').select('*').eq('user_id',user.id).maybeSingle();
 if(!profile){await supabaseClient.auth.signOut();Cstatus('clLoginStatus','No client profile is linked to this account. Please create a client account or ask the designer to link your account.');return;}
 clientProfile=profile; C$('clientLogin').classList.add('hidden');C$('clientApp').classList.remove('hidden');C$('clientName').textContent=`Welcome, ${profile.name}`; await refreshClient(); startClientRealtime();
}
async function refreshClient(){
 const [{data:projects},{data:updates},{data:invoices},{data:messages},{data:notifs}]=await Promise.all([
  supabaseClient.from('projects').select('*').eq('client_id',clientProfile.id).order('created_at',{ascending:false}),
  supabaseClient.from('work_updates').select('*').eq('client_id',clientProfile.id).order('created_at',{ascending:false}),
  supabaseClient.from('invoices').select('*').eq('client_id',clientProfile.id).order('created_at',{ascending:false}),
  supabaseClient.from('client_messages').select('*').eq('client_id',clientProfile.id).order('created_at',{ascending:true}),
  supabaseClient.from('client_notifications').select('*').eq('client_id',clientProfile.id).is('read_at',null)
 ]);
 const p=projects||[],u=updates||[],inv=invoices||[],msgs=messages||[]; C$('statProjects').textContent=p.length;C$('statInvoices').textContent=inv.length;C$('statUpdates').textContent=u.length;
 C$('clientProjects').innerHTML=p.map(x=>`<div class="admin-item"><div><strong>${esc(x.title)}</strong><div class="muted">${esc(x.category||'')} · ${esc(x.status||'Planning')}</div><p>${esc(x.description||'')}</p></div>${(x.image_path||x.image_url)?`<img src="${safeImage(x.image_path ? supabaseClient.storage.from('portfolio').getPublicUrl(x.image_path).data.publicUrl : x.image_url)}" onerror="this.src='assets/background.png'">`:''}</div>`).join('')||'<p class="muted">No projects assigned yet.</p>';
 const updateHtml=u.map(x=>`<div class="admin-item"><div><strong>${esc(x.title)}</strong><div class="muted">${esc(x.status||'In progress')} · ${new Date(x.created_at).toLocaleDateString()}</div><p>${esc(x.description||'')}</p></div></div>`).join('')||'<p class="muted">No work updates yet.</p>';C$('clientUpdates').innerHTML=updateHtml;C$('overviewUpdates').innerHTML=updateHtml;
 const rows=[]; for(const i of inv){const {data:items}=await supabaseClient.from('invoice_items').select('*').eq('invoice_id',i.id);const total=(items||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_price||0),0);rows.push(`<div class="invoice-card"><div class="invoice-head"><strong>${esc(i.invoice_number)}</strong><span class="tag">${esc(i.status)}</span></div><div class="muted">Issued ${esc(i.issue_date||'')} · Due ${esc(i.due_date||'')}</div><div class="invoice-total">${money(total,i.currency)}</div><details><summary>View invoice</summary><div class="invoice-lines">${(items||[]).map(x=>`<div><span>${esc(x.description)} × ${x.quantity}</span><strong>${money(Number(x.quantity)*Number(x.unit_price),i.currency)}</strong></div>`).join('')}</div><p>${esc(i.notes||'')}</p><button class="btn" onclick="printInvoice('${i.id}')">Print / Save PDF</button></details></div>`)} C$('clientInvoices').innerHTML=rows.join('')||'<p class="muted">No invoices yet.</p>';
 C$('clientMessages').innerHTML=msgs.map(m=>`<div class="message-card ${m.sender_type==='admin'?'from-admin':'from-client'}"><strong>${m.sender_type==='admin'?'Jehoshaphat':'You'}</strong><div>${esc(m.message)}</div><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No messages yet.</p>'; C$('clientMessages').scrollTop=C$('clientMessages').scrollHeight;
 const unread=(msgs.filter(m=>m.sender_type==='admin'&&!m.read_at).length)+(notifs||[]).length; const b=C$('clientMsgBadge');b.textContent=unread;b.classList.toggle('hidden',!unread);
 if((notifs||[]).length) await supabaseClient.from('client_notifications').update({read_at:new Date().toISOString()}).eq('client_id',clientProfile.id).is('read_at',null);
}
window.printInvoice=async id=>{const {data:i}=await supabaseClient.from('invoices').select('*').eq('id',id).single();const {data:items}=await supabaseClient.from('invoice_items').select('*').eq('invoice_id',id);const total=(items||[]).reduce((s,x)=>s+Number(x.quantity)*Number(x.unit_price),0);const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(i.invoice_number)}</title><style>body{font:16px Arial;padding:40px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{text-align:right;font-size:22px}</style></head><body><h1>JEHOSHAPHAT MENDS</h1><h2>${esc(i.invoice_number)}</h2><p>Issued: ${esc(i.issue_date)}<br>Due: ${esc(i.due_date||'')}</p><table><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr>${(items||[]).map(x=>`<tr><td>${esc(x.description)}</td><td>${x.quantity}</td><td>${money(x.unit_price,i.currency)}</td><td>${money(x.quantity*x.unit_price,i.currency)}</td></tr>`).join('')}</table><p class="total">Total: ${money(total,i.currency)}</p><p>${esc(i.notes||'')}</p><script>window.print()<\/script></body></html>`);w.document.close()};
function startClientRealtime(){if(clientMessageChannel)return;clientMessageChannel=supabaseClient.channel('client-portal-'+clientProfile.id).on('postgres_changes',{event:'*',schema:'public',table:'client_messages',filter:`client_id=eq.${clientProfile.id}`},refreshClient).on('postgres_changes',{event:'*',schema:'public',table:'client_notifications',filter:`client_id=eq.${clientProfile.id}`},refreshClient).subscribe();}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');C$('clientLoginForm').classList.toggle('hidden',b.dataset.authTab!=='login');C$('clientSignupForm').classList.toggle('hidden',b.dataset.authTab!=='signup')});
C$('clientLoginForm').onsubmit=async e=>{e.preventDefault();Cstatus('clLoginStatus','Signing in...');const {data,error}=await supabaseClient.auth.signInWithPassword({email:C$('clEmail').value,password:C$('clPassword').value});if(error){Cstatus('clLoginStatus',error.message);return;}await loadClient();};
C$('clientSignupForm').onsubmit=async e=>{e.preventDefault();Cstatus('clSignupStatus','Creating account...');const {data,error}=await supabaseClient.auth.signUp({email:C$('csEmail').value,password:C$('csPassword').value,options:{data:{account_type:'client',full_name:C$('csName').value,company:C$('csCompany').value,phone:C$('csPhone').value}}});if(error){Cstatus('clSignupStatus',error.message);return;}if(!data.user){Cstatus('clSignupStatus','Check your email to confirm your account, then return here to log in.');return;}Cstatus('clSignupStatus',data.session?'Account created. Loading your portal...':'Account created. Check your email if confirmation is required, then log in.');if(data.session) await loadClient();};
C$('clientMessageForm').onsubmit=async e=>{e.preventDefault();const text=C$('clientMessageText').value.trim();if(!text)return;Cstatus('clientMessageStatus','Sending...');const {error}=await supabaseClient.from('client_messages').insert({client_id:clientProfile.id,sender_type:'client',message:text});Cstatus('clientMessageStatus',error?error.message:'Message sent.');if(!error){C$('clientMessageText').value='';await refreshClient();}};
C$('clientLogout').onclick=async()=>{if(clientMessageChannel)await supabaseClient.removeChannel(clientMessageChannel);await supabaseClient.auth.signOut();location.reload()};
document.querySelectorAll('[data-client-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-client-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.client-section').forEach(x=>x.classList.remove('active'));C$(b.dataset.clientTab).classList.add('active');});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));} function safeImage(v){return v||'assets/background.png'}
loadClient();
