let companyClients=[],companyProjects=[]; const A$=id=>document.getElementById(id); const Ast=(id,m)=>{if(A$(id))A$(id).textContent=m||''};
async function companyLoad(){
 const [{data:c},{data:p},{data:u},{data:i}]=await Promise.all([supabaseClient.from('clients').select('*').order('created_at',{ascending:false}),supabaseClient.from('projects').select('*').order('created_at',{ascending:false}),supabaseClient.from('work_updates').select('*,clients(name),projects(title)').order('created_at',{ascending:false}),supabaseClient.from('invoices').select('*,clients(name)').order('created_at',{ascending:false})]);
 companyClients=c||[];companyProjects=p||[]; fillClientSelects(); renderClients(); renderUpdates(u||[]); renderInvoices(i||[]); await renderAdminMessages();
}
function fillClientSelects(){['updateClient','invoiceClient','messageClient'].forEach(id=>{const s=A$(id);if(s)s.innerHTML='<option value="">Select client</option>'+companyClients.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.email)}</option>`).join('')});const ps=A$('updateProject');if(ps)ps.innerHTML='<option value="">No project</option>'+companyProjects.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('');}
function renderClients(){A$('clientList').innerHTML=companyClients.map(c=>`<div class="admin-item"><div><strong>${esc(c.name)}</strong><div class="muted">${esc(c.company||'')} · ${esc(c.email)}</div></div><div class="actions"><button class="btn" onclick="editClient('${c.id}')">Edit</button><button class="btn" onclick="deleteClient('${c.id}')">Delete</button></div></div>`).join('')||'<p class="muted">No clients.</p>';}
window.editClient=id=>{const c=companyClients.find(x=>x.id===id);A$('clientId').value=c.id;A$('clientNameInput').value=c.name;A$('clientEmailInput').value=c.email;A$('clientCompanyInput').value=c.company||'';A$('clientPhoneInput').value=c.phone||'';};
window.deleteClient=async id=>{if(!confirm('Delete this client and their portal records?'))return;const {error}=await supabaseClient.from('clients').delete().eq('id',id);if(error){alert(error.message);return;}await companyLoad()};
A$('clientForm').onsubmit=async e=>{e.preventDefault();const id=A$('clientId').value;const row={name:A$('clientNameInput').value,email:A$('clientEmailInput').value.toLowerCase(),company:A$('clientCompanyInput').value,phone:A$('clientPhoneInput').value};const q=id?supabaseClient.from('clients').update(row).eq('id',id):supabaseClient.from('clients').insert(row);const {error}=await q;Ast('clientStatusAdmin',error?.message||'Client saved.');if(!error){A$('clientForm').reset();A$('clientId').value='';await companyLoad()}};A$('clearClient').onclick=()=>{A$('clientForm').reset();A$('clientId').value=''};
function renderUpdates(rows){A$('updateList').innerHTML=rows.map(x=>`<div class="admin-item"><div><strong>${esc(x.title)}</strong><div class="muted">${esc(x.clients?.name||'')} · ${esc(x.status)}</div><p>${esc(x.description||'')}</p></div><button class="btn" onclick="deleteUpdate('${x.id}')">Delete</button></div>`).join('')||'<p class="muted">No updates.</p>'}
window.deleteUpdate=async id=>{if(!confirm('Delete this work update?'))return;await supabaseClient.from('work_updates').delete().eq('id',id);companyLoad()};A$('updateForm').onsubmit=async e=>{e.preventDefault();const row={client_id:A$('updateClient').value,project_id:A$('updateProject').value||null,title:A$('updateTitle').value,description:A$('updateDescription').value,status:A$('updateStatus').value};const {error}=await supabaseClient.from('work_updates').insert(row);Ast('updateStatusMsg',error?.message||'Work update posted.');if(!error){A$('updateForm').reset();await companyLoad()}};
function renderInvoices(rows){A$('invoiceAdminList').innerHTML=rows.map(x=>`<div class="invoice-card"><div class="invoice-head"><strong>${esc(x.invoice_number)}</strong><span>${esc(x.clients?.name||'')} · ${esc(x.status)}</span></div><div class="muted">Due ${esc(x.due_date||'')}</div><button class="btn" onclick="deleteInvoice('${x.id}')">Delete</button></div>`).join('')||'<p class="muted">No invoices.</p>'};window.deleteInvoice=async id=>{if(!confirm('Delete this invoice and its items?'))return;await supabaseClient.from('invoices').delete().eq('id',id);companyLoad()};
function addInvoiceItem(){const wrap=A$('invoiceItems');const div=document.createElement('div');div.className='invoice-item-editor';div.innerHTML='<input class="ii-desc" placeholder="Description" required><input class="ii-qty" type="number" min="0" step="0.01" value="1" required><input class="ii-price" type="number" min="0" step="0.01" value="0" required><button type="button" class="btn" onclick="this.parentElement.remove()">Remove</button>';wrap.appendChild(div)}window.addInvoiceItem=addInvoiceItem;A$('addInvoiceItem').onclick=addInvoiceItem;addInvoiceItem();
A$('invoiceForm').onsubmit=async e=>{e.preventDefault();const {data:i,error}=await supabaseClient.from('invoices').insert({client_id:A$('invoiceClient').value,invoice_number:A$('invoiceNumber').value, due_date:A$('invoiceDue').value||null,status:A$('invoiceStatus').value,currency:A$('invoiceCurrency').value||'GHS',notes:A$('invoiceNotes').value}).select().single();if(error){Ast('invoiceStatusMsg',error.message);return;}const items=[...document.querySelectorAll('.invoice-item-editor')].map(x=>({invoice_id:i.id,description:x.querySelector('.ii-desc').value,quantity:Number(x.querySelector('.ii-qty').value),unit_price:Number(x.querySelector('.ii-price').value)}));const {error:ie}=await supabaseClient.from('invoice_items').insert(items);Ast('invoiceStatusMsg',ie?.message||'Invoice created.');if(!ie){await supabaseClient.from('client_notifications').insert({client_id:i.client_id,title:'New invoice',body:`Invoice ${i.invoice_number} is available in your client portal.`});A$('invoiceForm').reset();A$('invoiceItems').innerHTML='';addInvoiceItem();await companyLoad()}};
async function renderAdminMessages(){const {data:msgs}=await supabaseClient.from('client_messages').select('*,clients(name,email)').order('created_at',{ascending:false});A$('adminClientMessageList').innerHTML=(msgs||[]).map(m=>`<div class="message-card ${m.sender_type==='admin'?'from-admin':'from-client'}"><strong>${esc(m.clients?.name||'Client')} · ${m.sender_type}</strong><div>${esc(m.message)}</div><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">No client messages.</p>'}
A$('adminMessageForm').onsubmit=async e=>{e.preventDefault();const clientId=A$('messageClient').value,text=A$('adminMessageText').value;const {error}=await supabaseClient.from('client_messages').insert({client_id:clientId,sender_type:'admin',message:text});if(!error)await supabaseClient.from('client_notifications').insert({client_id:clientId,title:'New message from Jehoshaphat',body:text});Ast('adminMessageStatus',error?.message||'Message sent to client portal.');if(!error){A$('adminMessageText').value='';await renderAdminMessages()}};
document.querySelectorAll('[data-company-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-company-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.company-section').forEach(x=>x.classList.remove('active'));A$(b.dataset.companyTab).classList.add('active')});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
